LogFile /data/adb/modules/clamguard/var/log/clamav/clamd.log
LogTime yes
Foreground yes
DatabaseDirectory /data/adb/modules/clamguard/db
LocalSocket /data/adb/modules/clamguard/var/clamd.sock
FixStaleSocket true
TCPSocket 0
User root
ScanPE yes
ScanELF yes
ScanOLE2 yes
ScanPDF yes
ScanHTML yes
ScanArchive yes
ScanMail yes
