DatabaseDirectory /data/adb/modules/clamguard/db
UpdateLogFile /data/adb/modules/clamguard/var/log/clamav/freshclam.log
LogTime yes
Foreground yes
DatabaseOwner root
Checks 12
DNSDatabaseInfo current.cvd.clamav.net
DatabaseMirror database.clamav.net
ConnectTimeout 30
ReceiveTimeout 60
TestDatabases yes
